dist: trusty
sudo: false

branches:
  only:
  - master

language: go

go:
  - "1.14.x"

before_install:
  - go get github.com/mattn/goveralls

install:
  - make deps

script:
  - hack/verify-codegen.sh
  - travis_wait 20 go test -race -covermode atomic -coverprofile=profile.cov ./pkg/... -v
  - goveralls -coverprofile=profile.cov -service=travis-ci -v
  - make e2e
